<html>
    <head>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
        <script typr="text/javascript">
            $(document).ready(function(){
               $('a').click(function(){
                  $('p').not('.important').slideToggle();
               });
           });
     </script>
    </head>
    <body>
        
        <p>Some Text</p>
        <p>Some More Text </p>
        <a href ="#">Toggle</a>
        <a href ="#">Toggle</a>
        <a href ="#">Toggle</a>
    </body>
</html>