<a id="city-search"href="<?php echo $this->baseUrl() . '/shop/index'; ?>">Search </a>
<table align="right" width="100%" border="1px solid black">
    <tr>
        <th> Shop Name        </th>
        <th> Address          </th>
        <th> Phone            </th>                
        <th> Edit            </th> 
        <th> Delete            </th> 
    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['name']; ?></td>
            <td><?php echo $result['address']; ?></td>
            <td><?php echo $result['phone']; ?></td>

            <td>
                <a href="<?php echo $this->url(array('controller' => 'shop', 'action' => 'edit', 'id' => $result['shop_id'])); ?>">Edit </a>
            </td>

            <td>
                <a href="<?php echo $this->url(array('controller' => 'shop', 'action' => 'delete', 'id' => $result['shop_id'])); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
$this->headScript()->appendFile($this->baseUrl() . "/common/js/ui/jquery.ui.core.js");
$this->headScript()->appendFile($this->baseUrl() . "/common/js/ui/jquery.ui.widget.js");
$this->headScript()->appendFile($this->baseUrl() . "/common/js/ui/jquery.ui.position.js");
$this->headLink()->appendStylesheet($this->baseUrl() . "/common/css/fancybox.css");
$this->headScript()->appendFile($this->baseUrl() . "/common/js/jquery.fancybox-1.3.4.js");
?>
<script type="text/javascript">
    $('#city-search').fancybox();
</script>