

<table align="right" width="100%" border="1px solid black">
    <tr>
        <th>    User   </th>
        <th>    Product     </th>
        <th>    Edit            </th>
        <th>    Delete          </th>

    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['user_name']; ?></td>
<!--            <td><?php echo $result['product_name']; ?></td>-->


            <td>
                <a href="<?php echo $this->url(array('controller' => 'book', 'action' => 'edit', 'id' => $result['book_id'])); ?>">Edit </a>
            </td>

            <td>
                <a href="<?php echo $this->url(array('controller' => 'book', 'action' => 'delete', 'id' => $result['book_id'])); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>    
